services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./aiqfav:/app/aiqfav
      - ./alembic:/app/alembic
    working_dir: /app
    command: uv run uvicorn aiqfav.api:app --host=0.0.0.0 --reload
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
